
import joblib
import pandas as pd
import numpy as np
import sys
import os

# Assuming model_v2.joblib is generated by train_pipeline.py in the same directory
MODEL_PATH = "model_v2.joblib"

def validate_model():
    print("Starting validation pipeline...")
    
    if not os.path.exists(MODEL_PATH):
        print(f"Error: Model file {MODEL_PATH} not found.")
        sys.exit(1)
        
    try:
        artifact = joblib.load(MODEL_PATH)
        print("Model loaded successfully.")
    except Exception as e:
        print(f"Error loading model: {e}")
        sys.exit(1)
        
    # Check Required Keys
    required_keys = [
        "model", "feature_columns", "cat_cols", 
        "cat_mappings", "broker_counts", 
        "broker_dominance", "broker_entropy"
    ]
    
    missing = [k for k in required_keys if k not in artifact]
    if missing:
        print(f"Validation Failed: Missing keys in artifact: {missing}")
        sys.exit(1)
        
    model = artifact["model"]
    feature_columns = artifact["feature_columns"]
    
    # Mock Inference Request
    print("Running inference test...")
    test_input = {
        "User_ID": [101, 102],
        "Broker_ID": ["B001", "B002"],
        "Broker_Agency_Type": ["National_Corporate", "Independent"],
        "Region_Code": ["PRT", "ESP"],
        "Deductible_Tier": ["Tier_1_High_Ded", "Tier_2_Mid_Ded"],
        "Acquisition_Channel": ["Direct_Website", "Broker_Referral"],
        "Broker_Count": [10, 5],
        "Broker_Dominance": [0.5, 0.2],
        "Broker_Entropy": [0.1, 0.8],
        "pat_cls8": [0, 1],
        "pat_cls9": [0, 0]
    }
    
    df = pd.DataFrame(test_input)
    
    # Ensure columns match expected features
    # (In production, preprocess() handles this, but here we validate raw model capability)
    X = df[feature_columns].copy() # Select features directly if they match
    
    # Handle categorical encoding for test input
    for col in artifact["cat_cols"]:
        if col in X.columns:
            mapping = artifact["cat_mappings"].get(col, {})
            # Mock mapping logic for test
            X[col] = X[col].map(mapping).fillna(-1) 
            
    try:
        preds = model.predict(X)
        print(f"Predictions: {preds}")
        if len(preds) != 2:
            print("Validation Failed: Incorrect number of predictions.")
            sys.exit(1)
    except Exception as e:
        print(f"Validation Failed: Prediction error: {e}")
        sys.exit(1)
        
    print("Validation Passed!")
    sys.exit(0)

if __name__ == "__main__":
    validate_model()
